### ISSUE TITLE
Help with the mod

### ISSUE THREAD

**Issue by eugenikus8** [Alchav/SpaceAgeWithoutSpace#1]
Hello. I really liked your mod. I went through almost the entire game with it and additionally using the Pneumatic Transport Repressurized mod https://mods.factorio.com/mod/pneumatic-transport-rp, where all objects can be turned into fluid and transported through pipes.
In Space Age, all items liquefy normally, but with your 'space-science-pack' mod it doesn't. 
I checked in EditorExtensions, 'promethium-science-pack' and 'space-science-pack' are not liquefied.
Can you help me figure this out?
Thanks for your mod.

**Comment by Alchav** [comment]
The Pneumatic Transport Repressurized mod says it "should work with any mod" but it creates its recipes in data.lua which makes it unlikely to catch recipes and items made by other mods. My mod makes most of its changes in data-updates.lua which runs after all mods' data.lua. So I think this is something the author of that mod would have to address.

**Comment by Alchav** [comment]
Okay I see that repo on your account, are you the maintainer of that mod?

**Comment by eugenikus8** [comment]
No. I made my version based on the original https://mods.factorio.com/mod/pneumatic-transport, not based on the fork. But they are the same in terms of conversion to liquid. But liquefaction doesn’t work in my version either. Although the requirement for fluids.lua is run in data-final-fixes.lua

**Comment by eugenikus8** [comment]
I tried adding your SpaceAgeWithoutSpace mod to info.json in 'dependencies' and changed the fixes from data.lua to data-final-fixes.lua but it had no effect.
